name:                cut-the-crap
version:             1.0.0
license:             MIT
synopsis:            Cut the crap is an automatic video editing program for streamers. It can cut out uninteresting parts by detecting silences. 
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2019 Jappie Klooster"

extra-source-files:
- Readme.md
- LICENSE

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    - -Widentities

# from https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
default-extensions:
  # trivial
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  # only activated once used
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  # no cost deriving power
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  # used everywhere anyway
  - OverloadedStrings
  # ehh syntax
  - TypeApplications

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- optparse-generic
- generic-lens
- shelly
- text
- lens
- exceptions
- unliftio-core
- temporary
- regex-tdfa
- system-filepath

library:
  source-dirs: src

executables:
  cut-the-crap:
    main:                exe.hs
    source-dirs:         app
    dependencies:
    - cut-the-crap
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  unit:
    main:                Spec.hs
    source-dirs:
    - test
    # including extra source dirs allows ghcid to watch
    - src 
    dependencies:
    - hspec
    - hspec-core
