name:                template
version:             1.0.0
github:              "jappeace/template"
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2019 Jappie Klooster"

extra-source-files:
- Readme.md

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    - -Widentities

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  exe:
    main:                exe.hs
    source-dirs:         app
    dependencies:
    - template
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
